trigger:
  batch: true

variables:
 AZURE_SUB_ID: $(AZURE_SUBSCRIPTION_ID)
 GH_TOKEN: $(GITHUB_TOKEN)



stages:
- stage: Build
  displayName: Build stage
  pool: 
    image: windows-1809
  jobs:
  - job: Build
    workspace:
      clean: all
    displayName: Build
    steps:
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: test-azurerm
        scriptType: inlineScript
        inline:
            Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force -AllowClobber
            Uninstall-AzureRm
            Import-Module .\helpers\GenerateResourcesAndImage.ps1
            GenerateResourcesAndImage -AzureClientId $(AZURECLIENTID) -AzureClientSecret $(AzureClientSecret) -AzureTenantId $(AzureTenantId) -SubscriptionId ca9a7991-a1c8-4951-a321-11e7c1ffc279 -ImageGenerationRepositoryRoot "$pwd" -ImageType windows2019 -AzureLocation "west US" -ResourceGroupName gs3-build-agent-images
      displayName: build resources
